version: "3"

services:

  web:
    build: .
    restart: unless-stopped
    command: gunicorn main:app -c config/gunicorn.conf.py
    volumes:
      - .:/src
      - ./logs/gunicorn:/var/log
    ports:
      - 8007:8000
    env_file:
      - .envs
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./databases/redis:/data
    ports:
      - 6380:6379